favoritos = [
{"id":"6","codigo":"BTC","descricao":"Bitcoin","ativo":"1"},
{"id":"36","codigo":"USD","descricao":"Dólar Americano","ativo":"1"},
{"id":"152","codigo":"XRP","descricao":"XRP","ativo":"1"},
]

data = [
{"id":"1","codigo":"AFN","descricao":"Afghani do Afeganistão","ativo":"0"},
{"id":"2","codigo":"MGA","descricao":"Ariary Madagascarense","ativo":"0"},
{"id":"3","codigo":"THB","descricao":"Baht Tailandês","ativo":"0"},
{"id":"4","codigo":"PAB","descricao":"Balboa Panamenho","ativo":"0"},
{"id":"5","codigo":"ETB","descricao":"Birr Etíope","ativo":"0"},
{"id":"6","codigo":"BTC","descricao":"Bitcoin","ativo":"1"},
{"id":"7","codigo":"BOB","descricao":"Boliviano","ativo":"0"},
{"id":"8","codigo":"VEF","descricao":"Bolívar Venezuelano","ativo":"0"},
{"id":"9","codigo":"XBR","descricao":"Brent Spot","ativo":"0"},
{"id":"10","codigo":"GHS","descricao":"Cedi Ganês","ativo":"0"},
{"id":"11","codigo":"SVC","descricao":"Colon de El Salvador","ativo":"0"},
{"id":"12","codigo":"CRC","descricao":"Colón Costarriquenho","ativo":"0"},
{"id":"13","codigo":"CZK","descricao":"Coroa Checa","ativo":"0"},
{"id":"14","codigo":"DKK","descricao":"Coroa Dinamarquesa","ativo":"0"},
{"id":"15","codigo":"ISK","descricao":"Coroa Islandesa","ativo":"0"},
{"id":"16","codigo":"NOK","descricao":"Coroa Norueguesa","ativo":"0"},
{"id":"17","codigo":"SEK","descricao":"Coroa Sueca","ativo":"0"},
{"id":"18","codigo":"NIO","descricao":"Córdoba Nicaraguense","ativo":"0"},
{"id":"19","codigo":"SDR","descricao":"DSE","ativo":"0"},
{"id":"20","codigo":"GMD","descricao":"Dalasi da Gâmbia","ativo":"0"},
{"id":"21","codigo":"MKD","descricao":"Denar Macedônio","ativo":"0"},
{"id":"22","codigo":"DZD","descricao":"Dinar Argelino","ativo":"0"},
{"id":"23","codigo":"IQD","descricao":"Dinar Iraquiano","ativo":"0"},
{"id":"24","codigo":"JOD","descricao":"Dinar Jordaniano","ativo":"0"},
{"id":"25","codigo":"KWD","descricao":"Dinar Kuwaitiano","ativo":"0"},
{"id":"26","codigo":"LYD","descricao":"Dinar Líbio","ativo":"0"},
{"id":"27","codigo":"RSD","descricao":"Dinar Sérvio","ativo":"0"},
{"id":"28","codigo":"TND","descricao":"Dinar Tunisiano","ativo":"0"},
{"id":"29","codigo":"BHD","descricao":"Dinar do Bahrein","ativo":"0"},
{"id":"30","codigo":"MAD","descricao":"Dirham Marroquino","ativo":"0"},
{"id":"31","codigo":"AED","descricao":"Dirham dos Emirados","ativo":"0"},
{"id":"32","codigo":"STD","descricao":"Dobra São Tomé/Príncipe","ativo":"0"},
{"id":"33","codigo":"DOGE","descricao":"Dogecoin","ativo":"0"},
{"id":"34","codigo":"VND","descricao":"Dong Vietnamita","ativo":"0"},
{"id":"35","codigo":"AMD","descricao":"Dram Armênio","ativo":"0"},
{"id":"36","codigo":"USD","descricao":"Dólar Americano","ativo":"1"},
{"id":"37","codigo":"AUD","descricao":"Dólar Australiano","ativo":"0"},
{"id":"38","codigo":"CAD","descricao":"Dólar Canadense","ativo":"0"},
{"id":"39","codigo":"JMD","descricao":"Dólar Jamaicano","ativo":"0"},
{"id":"40","codigo":"NAD","descricao":"Dólar Namíbio","ativo":"0"},
{"id":"41","codigo":"NZD","descricao":"Dólar Neozelandês","ativo":"0"},
{"id":"42","codigo":"TWD","descricao":"Dólar Taiuanês","ativo":"0"},
{"id":"43","codigo":"ZWL","descricao":"Dólar Zimbabuense","ativo":"0"},
{"id":"44","codigo":"BSD","descricao":"Dólar das Bahamas","ativo":"0"},
{"id":"45","codigo":"KYD","descricao":"Dólar das Ilhas Cayman","ativo":"0"},
{"id":"46","codigo":"BBD","descricao":"Dólar de Barbados","ativo":"0"},
{"id":"47","codigo":"BZD","descricao":"Dólar de Belize","ativo":"0"},
{"id":"48","codigo":"BND","descricao":"Dólar de Brunei","ativo":"0"},
{"id":"49","codigo":"SGD","descricao":"Dólar de Cingapura","ativo":"0"},
{"id":"50","codigo":"FJD","descricao":"Dólar de Fiji","ativo":"0"},
{"id":"51","codigo":"HKD","descricao":"Dólar de Hong Kong","ativo":"0"},
{"id":"52","codigo":"TTD","descricao":"Dólar de Trinidad","ativo":"0"},
{"id":"53","codigo":"XCD","descricao":"Dólar do Caribe Oriental","ativo":"0"},
{"id":"54","codigo":"CVE","descricao":"Escudo cabo-verdiano","ativo":"0"},
{"id":"55","codigo":"ETH","descricao":"Ethereum","ativo":"1"},
{"id":"56","codigo":"EUR","descricao":"Euro","ativo":"0"},
{"id":"57","codigo":"HUF","descricao":"Florim Húngaro","ativo":"0"},
{"id":"58","codigo":"BIF","descricao":"Franco Burundinense","ativo":"0"},
{"id":"59","codigo":"XAF","descricao":"Franco CFA Central","ativo":"0"},
{"id":"60","codigo":"XOF","descricao":"Franco CFA Ocidental","ativo":"0"},
{"id":"61","codigo":"XPF","descricao":"Franco CFP","ativo":"0"},
{"id":"62","codigo":"KMF","descricao":"Franco Comorense","ativo":"0"},
{"id":"63","codigo":"RWF","descricao":"Franco Ruandês","ativo":"0"},
{"id":"64","codigo":"CHF","descricao":"Franco Suíço","ativo":"0"},
{"id":"65","codigo":"CHFRTS","descricao":"Franco Suíço","ativo":"0"},
{"id":"66","codigo":"GNF","descricao":"Franco de Guiné","ativo":"0"},
{"id":"67","codigo":"DJF","descricao":"Franco do Djubouti","ativo":"0"},
{"id":"68","codigo":"HTG","descricao":"Gourde Haitiano","ativo":"0"},
{"id":"69","codigo":"PYG","descricao":"Guarani Paraguaio","ativo":"0"},
{"id":"70","codigo":"ANG","descricao":"Guilder das Antilhas","ativo":"0"},
{"id":"71","codigo":"UAH","descricao":"Hryvinia Ucraniana","ativo":"0"},
{"id":"72","codigo":"JPY","descricao":"Iene Japonês","ativo":"0"},
{"id":"73","codigo":"JPYRTS","descricao":"Iene Japonês","ativo":"0"},
{"id":"74","codigo":"PGK","descricao":"Kina Papua-Nova Guiné","ativo":"0"},
{"id":"75","codigo":"LAK","descricao":"Kip Laosiano","ativo":"0"},
{"id":"76","codigo":"HRK","descricao":"Kuna Croata","ativo":"0"},
{"id":"77","codigo":"MWK","descricao":"Kwacha Malauiana","ativo":"0"},
{"id":"78","codigo":"ZMK","descricao":"Kwacha Zambiana","ativo":"0"},
{"id":"79","codigo":"AOA","descricao":"Kwanza Angolano","ativo":"0"},
{"id":"80","codigo":"MMK","descricao":"Kyat de Mianmar","ativo":"0"},
{"id":"81","codigo":"GEL","descricao":"Lari Georgiano","ativo":"0"},
{"id":"82","codigo":"ALL","descricao":"Lek Albanês","ativo":"0"},
{"id":"83","codigo":"HNL","descricao":"Lempira Hondurenha","ativo":"0"},
{"id":"84","codigo":"MDL","descricao":"Leu Moldavo","ativo":"0"},
{"id":"85","codigo":"RON","descricao":"Leu Romeno","ativo":"0"},
{"id":"86","codigo":"BGN","descricao":"Lev Búlgaro","ativo":"0"},
{"id":"87","codigo":"EGP","descricao":"Libra Egípcia","ativo":"0"},
{"id":"88","codigo":"GBP","descricao":"Libra Esterlina","ativo":"0"},
{"id":"89","codigo":"LBP","descricao":"Libra Libanesa","ativo":"0"},
{"id":"90","codigo":"SDG","descricao":"Libra Sudanesa","ativo":"0"},
{"id":"91","codigo":"SYP","descricao":"Libra Síria","ativo":"0"},
{"id":"92","codigo":"SZL","descricao":"Lilangeni Suazilandês","ativo":"0"},
{"id":"93","codigo":"LTC","descricao":"Litecoin","ativo":"0"},
{"id":"94","codigo":"LSL","descricao":"Loti do Lesoto","ativo":"0"},
{"id":"95","codigo":"AZN","descricao":"Manat Azeri","ativo":"0"},
{"id":"96","codigo":"BAM","descricao":"Marco Conversível","ativo":"0"},
{"id":"97","codigo":"MZN","descricao":"Metical de Moçambique","ativo":"0"},
{"id":"98","codigo":"MNT","descricao":"Mongolian Tugrik","ativo":"0"},
{"id":"99","codigo":"NGNPARALLEL","descricao":"Naira Nigeriana","ativo":"0"},
{"id":"100","codigo":"NGN","descricao":"Naira Nigeriana","ativo":"0"},
{"id":"101","codigo":"NGNI","descricao":"Naira Nigeriana","ativo":"0"},
{"id":"102","codigo":"TRY","descricao":"Nova Lira Turca","ativo":"0"},
{"id":"103","codigo":"ILS","descricao":"Novo Shekel Israelense","ativo":"0"},
{"id":"104","codigo":"MRO","descricao":"Ouguiya Mauritana","ativo":"0"},
{"id":"105","codigo":"MOP","descricao":"Pataca de Macau","ativo":"0"},
{"id":"106","codigo":"ARS","descricao":"Peso Argentino","ativo":"0"},
{"id":"107","codigo":"CLP","descricao":"Peso Chileno","ativo":"0"},
{"id":"108","codigo":"COP","descricao":"Peso Colombiano","ativo":"0"},
{"id":"109","codigo":"CUP","descricao":"Peso Cubano","ativo":"0"},
{"id":"110","codigo":"DOP","descricao":"Peso Dominicano","ativo":"0"},
{"id":"111","codigo":"PHP","descricao":"Peso Filipino","ativo":"0"},
{"id":"112","codigo":"MXN","descricao":"Peso Mexicano","ativo":"0"},
{"id":"113","codigo":"UYU","descricao":"Peso Uruguaio","ativo":"0"},
{"id":"114","codigo":"BWP","descricao":"Pula de Botswana","ativo":"0"},
{"id":"115","codigo":"GTQ","descricao":"Quetzal Guatemalteco","ativo":"0"},
{"id":"116","codigo":"ZAR","descricao":"Rand Sul-Africano","ativo":"0"},
{"id":"117","codigo":"BRL","descricao":"Real Brasileiro","ativo":"1"},
{"id":"118","codigo":"BRLT","descricao":"Real Brasileiro Turismo","ativo":"1"},
{"id":"119","codigo":"QAR","descricao":"Rial Catarense","ativo":"0"},
{"id":"120","codigo":"IRR","descricao":"Rial Iraniano","ativo":"0"},
{"id":"121","codigo":"OMR","descricao":"Rial Omanense","ativo":"0"},
{"id":"122","codigo":"KHR","descricao":"Riel Cambojano","ativo":"0"},
{"id":"123","codigo":"MYR","descricao":"Ringgit Malaio","ativo":"0"},
{"id":"124","codigo":"YER","descricao":"Riyal Iemenita","ativo":"0"},
{"id":"125","codigo":"SAR","descricao":"Riyal Saudita","ativo":"0"},
{"id":"126","codigo":"BYN","descricao":"Rublo Bielorrusso","ativo":"0"},
{"id":"127","codigo":"RUBTOM","descricao":"Rublo Russo","ativo":"0"},
{"id":"128","codigo":"RUBTOD","descricao":"Rublo Russo","ativo":"0"},
{"id":"129","codigo":"RUB","descricao":"Rublo Russo","ativo":"0"},
{"id":"130","codigo":"MVR","descricao":"Rufiyaa Maldiva","ativo":"0"},
{"id":"131","codigo":"IDR","descricao":"Rupia Indonésia","ativo":"0"},
{"id":"132","codigo":"INR","descricao":"Rúpia Indiana","ativo":"0"},
{"id":"133","codigo":"MUR","descricao":"Rúpia Mauriciana","ativo":"0"},
{"id":"134","codigo":"NPR","descricao":"Rúpia Nepalesa","ativo":"0"},
{"id":"135","codigo":"PKR","descricao":"Rúpia Paquistanesa","ativo":"0"},
{"id":"136","codigo":"LKR","descricao":"Rúpia de Sri Lanka","ativo":"0"},
{"id":"137","codigo":"SCR","descricao":"Rúpias de Seicheles","ativo":"0"},
{"id":"138","codigo":"KES","descricao":"Shilling Queniano","ativo":"0"},
{"id":"139","codigo":"SOS","descricao":"Shilling Somaliano","ativo":"0"},
{"id":"140","codigo":"TZS","descricao":"Shilling Tanzaniano","ativo":"0"},
{"id":"141","codigo":"UGX","descricao":"Shilling Ugandês","ativo":"0"},
{"id":"142","codigo":"PEN","descricao":"Sol do Peru","ativo":"0"},
{"id":"143","codigo":"KGS","descricao":"Som Quirguistanês","ativo":"0"},
{"id":"144","codigo":"UZS","descricao":"Som Uzbequistanês","ativo":"0"},
{"id":"145","codigo":"TJS","descricao":"Somoni do Tajiquistão","ativo":"0"},
{"id":"146","codigo":"TMT","descricao":"TMT","ativo":"0"},
{"id":"147","codigo":"BDT","descricao":"Taka de Bangladesh","ativo":"0"},
{"id":"148","codigo":"KZT","descricao":"Tengue Cazaquistanês","ativo":"0"},
{"id":"149","codigo":"VUV","descricao":"Vatu de Vanuatu","ativo":"0"},
{"id":"150","codigo":"KRW","descricao":"Won Sul-Coreano","ativo":"0"},
{"id":"151","codigo":"XAGG","descricao":"XPrata","ativo":"0"},
{"id":"152","codigo":"XRP","descricao":"XRP","ativo":"0"},
{"id":"153","codigo":"CNY","descricao":"Yuan Chinês","ativo":"0"},
{"id":"154","codigo":"CNH","descricao":"Yuan chinês offshore","ativo":"0"},
{"id":"155","codigo":"PLN","descricao":"Zlóti Polonês","ativo":"0"},
]